### ISSUE TITLE
validate that peer id is valid peer id, not random string

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aquavm#161]
```
func getNeighbours(node_id: PeerId, topic: string) -> []PeerId:
  on node_id:
    k <- Op.string_to_b58(topic)
    nodes <- Kademlia.neighborhood(k, nil, nil)
  <- nodes

```
pass any string to peer id -> get hang.
expected -> wrong peer id error

**Comment by folex** [comment]
@dzmitry-lahoda can you show how you call it so it hangs?

From your description, it's not clear whether you pass random string as `node_id` or as `topic`

**Comment by dzmitry-lahoda** [comment]
```
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: test-integration-testnet
  console.warn
    ping---------------------------------------

      12 |
      13 |   public warn(message?: any): void {
    > 14 |     console.warn(message);
         |             ^
      15 |   }
      16 |
      17 |   public debug(message?: any): void {

      at ConsoleLogger.warn (tests/logger/ConsoleLogger.ts:14:13)
      at tests/logger/ConsoleLogger.ts:24:14
      at generated/ts/Utils.ts:352:29
      at node_modules/@fluencelabs/fluence/src/internal/CallServiceHandler.ts:229:21
      at node_modules/@fluencelabs/fluence/src/internal/CallServiceHandler.ts:229:42
      at node_modules/@fluencelabs/fluence/src/internal/CallServiceHandler.ts:120:9
      at node_modules/@fluencelabs/fluence/src/internal/CallServiceHandler.ts:229:21

  console.warn
    {
      particleId: 'b08439e8-c1d8-459a-be37-f6b03047b0ed',
      initPeerId: '12D3KooWB9Ced2xe67yS8G83AhKGNr9nvM4VBFoWc7oW1x9uRGrH',
      timestamp: 1634383575586,
      ttl: 7000,
      signature: '',
      tetraplets: { arg0: [ [Object] ] }
    }

      12 |
      13 |   public warn(message?: any): void {
    > 14 |     console.warn(message);
         |             ^
      15 |   }
      16 |
      17 |   public debug(message?: any): void {

      at ConsoleLogger.warn (tests/logger/ConsoleLogger.ts:14:13)
      at tests/logger/ConsoleLogger.ts:25:14
      at generated/ts/Utils.ts:352:29
      at node_modules/@fluencelabs/fluence/src/internal/CallServiceHandler.ts:229:21
      at node_modules/@fluencelabs/fluence/src/internal/CallServiceHandler.ts:229:42
      at node_modules/@fluencelabs/fluence/src/internal/CallServiceHandler.ts:120:9
      at node_modules/@fluencelabs/fluence/src/internal/CallServiceHandler.ts:229:21

  console.error
    after ping........................
```

**Comment by dzmitry-lahoda** [comment]
```
func ping(ping: string, log : string -> ()) -> string:
    force_wait: *string
    on "42":
        log("ping---------------------------------------")
        force_wait <<- "pong"
    <- force_wait!0
```

**Comment by dzmitry-lahoda** [comment]
how that can be? please document behavior of `on` in case of wrings ids. it seems depends if wrong ON was called in browser on in node.

**Comment by dzmitry-lahoda** [comment]
`on node_id:` - if pass not peer id here, random stuff happens.

**Comment by mikevoronov** [comment]
Close this issue, because it's more Aqua then AquaVM. @alari @DieMyst could you please check do we need to move this issue to the `aqua` repo?
